package cluster

import (
	"fmt"
	"strings"

	"github.com/mwiget/dpubnkctl/internal/poc"
	"github.com/mwiget/dpubnkctl/internal/version"
)

func renderOfflineYML(p *poc.PoC) string {
	if p.Airgap == nil {
		return ""
	}
	ip := p.Airgap.JumphostIP
	kubeVer := strings.TrimPrefix(version.K8sVersionPinned, "v")

	return fmt.Sprintf(`# group_vars/all/offline.yml — generated by dpubnkctl (airgap mode)
registry_host: "%[1]s:5000"
files_repo: "http://%[1]s:8888"

kube_image_repo: "%[1]s:5000"
gcr_image_repo: "%[1]s:5000"
docker_image_repo: "%[1]s:5000"
quay_image_repo: "%[1]s:5000"
github_image_repo: "%[1]s:5000"

kube_version: "%[2]s"

github_url: "{{ files_repo }}/github.com"
dl_k8s_io_url: "{{ files_repo }}/dl.k8s.io"
`, ip, kubeVer)
}

func renderContainerdYML(p *poc.PoC) string {
	if p.Airgap == nil {
		return ""
	}
	ip := p.Airgap.JumphostIP

	mirror := fmt.Sprintf(`      - host: "https://%s:5000"
        capabilities: ["pull", "resolve"]
        skip_verify: true`, ip)

	prefixes := []string{
		ip + ":5000",
		"registry.k8s.io",
		"quay.io",
		"docker.io",
		"ghcr.io",
		"repo.f5.com",
	}

	var b strings.Builder
	b.WriteString("# group_vars/all/containerd.yml — generated by dpubnkctl (airgap mode)\n")
	b.WriteString("containerd_registries_mirrors:\n")
	for _, prefix := range prefixes {
		fmt.Fprintf(&b, "  - prefix: \"%s\"\n    mirrors:\n%s\n", prefix, mirror)
	}
	return b.String()
}
